


* Notes

Initial Formula was setup like this

#+BEGIN_SRC sh
brew create https://github.com/jkitchin/scimax/archive/refs/heads/master.zip
#+END_SRC

this created /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/scimax.rb

I moved it to [[./Formula/scimax.rb]], and have edited it extensively.

See the [[./makefile]] for useful build commands.

* build notes

** DONE an issue with the zip file is it is not a git clone, so the submodules do not work right.
CLOSED: [2023-04-26 Wed 07:55]

I figured out how to get the git repo, working. it requires head, and might make versioning trickier later. Maybe I can do something with tags.

This 
[[/usr/local/Cellar/scimax/HEAD-7c147b0]]

** DONE update user files
CLOSED: [2024-02-09 Fri 14:59]

These should be moved to something like ~/.emacs.d/scimax or ~/.config/scimax, or some user-defined space (I guess by env-var?).


** DONE setup the tap
CLOSED: [2024-02-09 Fri 14:59]

https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap


* other brew formula to learn from

Check out https://github.com/d12frosted/homebrew-emacs-plus

especially https://github.com/d12frosted/homebrew-emacs-plus/blob/master/build (a build script)

https://github.com/d12frosted/homebrew-emacs-plus/blob/master/Formula/emacs-plus%4028.rb



* brew notes

#+BEGIN_SRC sh
brew --repository
#+END_SRC

#+RESULTS:
: /usr/local/Homebrew

brew variables
https://docs.brew.sh/Formula-Cookbook#variables-for-directory-locations


** Taps

https://docs.brew.sh/Taps

See [[/usr/local/Homebrew/Library/Taps/]]
