#+title: Install scimax with homebrew
#+author: John Kitchin

#+BEGIN_HTML
<a href="https://github.com/jkitchin/homebrew-scimax/actions/workflows/scimax.yml"><img src="https://github.com/jkitchin/homebrew-scimax/actions/workflows/scimax.yml/badge.svg"></a>

<a href="https://github.com/jkitchin/homebrew-scimax/actions/workflows/scimax-windows.yml"><img src="https://github.com/jkitchin/homebrew-scimax/actions/workflows/scimax-windows.yml/badge.svg"></a>
#+END_HTML

The goal of this repo is to make a Tap for homebrew to install scimax and dependencies. 

* Installation

** Prerequisites

scimax needs working installations of Emacs, texlive and Python + Jupyter.

If you need an Emacs, I recommend you run this:

#+BEGIN_SRC sh
brew tap d12frosted/emacs-plus
brew install emacs-plus@28
#+END_SRC

If you need texlive for making LaTeX and pdf files you should run:

#+BEGIN_SRC sh
brew install texlive
#+END_SRC

Finally, you probably need to install Anaconda Python. This is a cask, so install it like this. This may be Mac specific. You can also install it from https://www.anaconda.com/download/. Other Python installations may work, but this one is the easiest and has most of what you need.

#+BEGIN_SRC sh
brew install --cask anaconda
#+END_SRC


** Installing scimax

After those, you can install scimax like this.

#+BEGIN_SRC sh
brew tap jkitchin/homebrew-scimax
$ brew install scimax
#+END_SRC




* Goals
1. install scimax with dependencies
   1. Emacs-plus@28 (optional)
   2. git https://formulae.brew.sh/formula/git#default
   3. coreutils https://formulae.brew.sh/formula/coreutils#default
   4. curl https://formulae.brew.sh/formula/curl#default
   5. cask https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/cask.rb
   6. aspell https://formulae.brew.sh/formula/aspell#default
   7. enchant https://formulae.brew.sh/formula/enchant#default
   8. ag https://formulae.brew.sh/formula/the_silver_searcher#default
   9. grep https://formulae.brew.sh/formula/grep#default
   10. latex (texlive) https://formulae.brew.sh/formula/texlive#default (optional)
   11. python  https://formulae.brew.sh/cask/anaconda (optional)
   12. wkhtmltodpf https://formulae.brew.sh/cask/wkhtmltopdf#default
   13. tesseract https://formulae.brew.sh/formula/tesseract#default

2. create a command called scimax

   1. runs something like "emacs -q -l $(scimax-dir)/init.el"

* issues

- [ ] confirm where user files go
- [ ] make sure you can still install new packages.
