name: scimax-windows

on:
  push:
    branches:
      - main
#    paths:
#      - "Formula/scimax.rb"      

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
      - uses: Vampire/setup-wsl@v2
      - run: net user
      - uses: actions/checkout@v3
      - uses: Vampire/setup-wsl@v2
        with:
          wsl-shell-user: runneradmin
          wsl-shell-command: sudo apt update && apt-get install --yes build-essential curl file git && /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" && HOMEBREW_NO_INSTALL_FROM_API=1 ~/.linuxbrew/bin/brew install --head ./Formula/scimax.rb

          
          

          

