name: scimax-windows

on:
  push:
    branches:
      - main
#    paths:
#      - "Formula/scimax.rb"      

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: Vampire/setup-wsl@v2
        with:
          wsl-shell-user: linuxbrew

      - shell: wsl-bash -u root {0}
        run: |
          whoami
          apt update && apt-get install --yes build-essential curl file git

      - shell: wsl-bash -u linuxbrew {0}
        run : |          
          whoami
          which curl
          which git
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
          brew doctor
          echo "Done with brew install"
          HOMEBREW_NO_INSTALL_FROM_API=1 brew install --head --verbose --formula ./Formula/scimax.rb
          echo "Done with scimax install"
          
          

          

