name: scimax-windows

on:
  push:
    branches:
      - main
#    paths:
#      - "Formula/scimax.rb"      

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:

      - uses: actions/checkout@v3
      - name: Install WSL
        uses: Vampire/setup-wsl@v2
        with:
          wsl-shell-user: linuxbrew

      - shell: wsl-bash {0}
        run: |
          whoami
          sudo apt update && apt-get install --yes build-essential curl file git
# && /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" && HOMEBREW_NO_INSTALL_FROM_API=1 ~/.linuxbrew/bin/brew install --head ./Formula/scimax.rb

          
          

          

