name: scimax-windows

on:
  push:
    branches:
      - main
#    paths:
#      - "Formula/scimax.rb"      

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: Vampire/setup-wsl@v2
      - shell: wsl-bash {0}
        run: |
          sudo apt update
          sudo apt-get install build-essential curl file git
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)" 
          brew install --head ./Formula/scimax.rb

          

