name: scimax

on:
  push:
    branches:
      - main
    paths:
      - "Formula/scimax.rb"      

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # windows-latest does not work
        # setting up homebrew fails
        # /usr/bin/bash: /D:/a/_actions/Homebrew/actions/master/setup-homebrew/main.sh: No such file or directory
        # ubuntu test takes ~7min
        # mac test is very slow...
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: Homebrew/actions/setup-homebrew@master

      - name: Build scimax 
        run: brew install --head ./Formula/scimax.rb
